### ISSUE TITLE
How do pre-authorized transactions actually work? 

### ISSUE THREAD

**Issue by vladfaust** [stellar/go#240]
In my opinion, [current documentation](https://www.stellar.org/developers/guides/concepts/multi-sig.html#pre-authorized-transaction) lacks of good example.

I came up with a simple "escrow" model. Let's say A wants to sell his 30 XLM offchain for real-world USD and B wants to buy it. An escrow account C is set up with two pre-authorized transactions which will result either in successful transfer or cancellation. Therefore, only four outcomes are possible:

- B sends USD and gets his 30 XLM, A is returned with 20 XLM (success)
- Both A and B agree on cancellation and A gets his 50 XLM back (cancel)
- B sends USD but A goes away losing his 50 XLM (A frauds and gets punished)
- B neither sends USD not cancels, so A is fu**ed up (the worst scenario)

Let's skip postponed refunding or B's insurance deposit for the sake of simplicity.

```yaml
# tx1
source: A
seq: A's sequence
ops:
  - create escrow account C with 50 XLM balance
  - add tx2 hash as signer with weight 1
  - add tx3 hash as signer with weight 1
  - set master key weight to 0
signers:
  - A
  - C

# tx2 (success)
source: ?
seq: C's sequence
ops:
  - send 30 XLM to B
  - merge C with A
signers:
  - ?

# tx3 (cancel)
source: ?
seq: C's sequence
ops:
  - send 30 XLM to A
  - merge C with A
signers:
  - ?
```

As far as I understand, to initiate the exchange, A has to sign tx1 and what's next? Who signs tx2 and tx3 and how will it work out? If we try to submit tx2 or tx3 signed by C it wont work out because C's master weight is already set to 0...

P.S: This paragraph is messed up:

> This type of signer is especially usefull in escrow accounts. You can create a pre-authorized transaction for two different transactions each with the same sequence number but that send to two different accounts. This means that only one of the pre-authorized transactions or the other will be able to execute.

You call "pre-authorized transaction" tx1 in the first sentence but in the last tx2 and tx3 become pre-authorized.
