### ISSUE TITLE
Install in standalone mode error

### ISSUE THREAD

**Issue by mymtw** [stellar/go#2833]
### What version are you using?
docker example as here https://github.com/stellar/go/tree/master/services/horizon/docker

### What did you do?
./start.sh standalone

### What did you expect to see?
start of nodes - stellar and horizon in standalone mode

### What did you see instead?

```
horizon_1       | time="2020-07-19T19:11:43.154Z" level=info msg="Ingestion system state machine transition" current_state=start next_state=start pid=1 service=expingest
horizon_1       | time="2020-07-19T19:11:43.157Z" level=error msg="Error in ingestion state machine" current_state=start error="Error getting last checkpoint: could not get root HAS: Get http://host.docker.internal:1570/.well-known/stellar-history.json: dial tcp 127.0.0.1:1570: connect: connection refused" next_state=start pid=1 service=expingest
horizon_1       | time="2020-07-19T19:11:43.950Z" level=warning msg="could not load stellar-core info: http request errored: Get http://host.docker.internal:11626/info: dial tcp 127.0.0.1:11626: connect: connect
```

my docker-compose.yml

```
version: "3.1"

services:
  postgres:
    image: postgres:11.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - /data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    network_mode: '${NETWORK_MODE:-bridge}'

  core:
    # to use a specific version of stellar core
    # image: stellar/stellar-core:$VERSION
    image: stellar/stellar-core
    depends_on:
      - postgres
    restart: always
    ports:
      - "11625:11625"
      - "11626:11626"
    command: /start
    volumes:
      - ./stellar-core-testnet.cfg:/stellar-core.cfg
      - ./core-start.sh:/start
    network_mode: '${NETWORK_MODE:-bridge}'

  horizon:
    depends_on:
      - postgres
      - core
    build:
      # set build context to the root directory of the go monorepo
      context: /home/mtw/Developer/go/src/gitlab.com/dart-m/payments/
      dockerfile: ./horizon/docker/Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://spotii:spotii@host.docker.internal:5432/horizon?sslmode=disable
      - STELLAR_CORE_DATABASE_URL=postgres://spotii:spotii@host.docker.internal:5432/stellar?sslmode=disable
      - HISTORY_ARCHIVE_URLS=https://history.stellar.org/prd/core-testnet/core_testnet_001
      # to connect to the public stellar network
      # - NETWORK_PASSPHRASE=Public Global Stellar Network ; September 2015
      - NETWORK_PASSPHRASE=Test SDF Network ; September 2015
      - STELLAR_CORE_URL=http://host.docker.internal:11626
      - INGEST=true
      - PER_HOUR_RATE_LIMIT=0
    network_mode: '${NETWORK_MODE:-bridge}'
    command: ["--apply-migrations"]
```

my docker-compose.standalone.yml

```
version: "3.1"
services:
  core:
    depends_on:
      - postgres
      - core-upgrade
    ports:
      # add extra port for history archive server
      - "1570:1570"
    command: /start standalone
    volumes:
      - ./stellar-core-standalone.cfg:/stellar-core.cfg
  horizon:
    environment:
      - HISTORY_ARCHIVE_URLS=http://host.docker.internal:1570
      - NETWORK_PASSPHRASE=Standalone Network ; February 2017
  # this container will invoke a request to upgrade stellar core to protocol 13
  core-upgrade:
    restart: on-failure
    image: curlimages/curl:7.69.1
    command: ["-v", "-f", "http://host.docker.internal:11626/upgrades?mode=set&upgradetime=1970-01-01T00:00:00Z&protocolversion=13"]
    network_mode: '${NETWORK_MODE:-bridge}'
```

my stellar-core-standalone.cfg

```
# simple configuration for a standalone test "network"
# see stellar-core_example.cfg for a description of the configuration parameters

RUN_STANDALONE=true

NETWORK_PASSPHRASE="Standalone Network ; February 2017"

PEER_PORT=11625
HTTP_PORT=11626
PUBLIC_HTTP_PORT=true

NODE_SEED="SACJC372QBSSKJYTV5A7LWT4NXWHTQO6GHG4QDAVC2XDPX6CNNXFZ4JK"

NODE_IS_VALIDATOR=true
UNSAFE_QUORUM=true
FAILURE_SAFETY=0

DATABASE="postgresql://user=spotii password=spotii host=host.docker.internal port=5432 dbname=stellar"

[QUORUM_SET]
THRESHOLD_PERCENT=100
VALIDATORS=["GD5KD2KEZJIGTC63IGW6UMUSMVUVG5IHG64HUTFWCHVZH2N2IBOQN7PS"]

[HISTORY.vs]
get="cp history/vs/{0} {1}"
put="cp {0} history/vs/{1}"
mkdir="mkdir -p history/vs/{0}"
```
