### ISSUE TITLE
Switch to toml files rather than env variables

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/go#85]

**Comment by dulanov** [comment]
Initial attempt on top of [docker-stellar-core-horizon's horizon.env](https://github.com/stellar/docker-stellar-core-horizon/blob/master/common/horizon/etc/horizon.env):

```toml
[core]
url = "http://localhost:11626"
database_url = "postgres://stellar:__PGPASS__@localhost/core"

[config]
database_url = "postgres://stellar:__PGPASS__@localhost/horizon"
ingest = true
log_level = "info"
network_passphrase="__NETWORK__"
per_hour_rate_limit = 72000
```

@jedmccaleb is it ok to start from?
